### ISSUE TITLE
MPS does not support stack unwinding under Windows when it is managing code

### ISSUE THREAD

**Issue by thejayps** [Ravenbrook/mps#212]
New memory acquired by the arena when the arena grows is not registered with Windows for stack debugging purposes. This is an issue in cases where the MPS stores code objects on the heap. 

This can be solved by implementing Arena extension and contraction callback functions, corresponding or similar to those previously implemented for Configura, and for which we now have permission from Configura to implement as part of the core MPS. These are documented here: https://www.ravenbrook.com/project/mps/custom/cet/main/manual/html/custom/cet/extension.html

A use case for these callbacks would involve the mutator calling RtlInstallFunctionTableCallback when it is notified via callback that the arena has grown.

**Comment by rptb1** [comment]
The arena extension/contraction callbacks were originally implemented in 2013 by me in Perforce changelist 182695.
