### ISSUE TITLE
Large hash tables can result in a feedback loop of collections and reallocations of the hash table

### ISSUE THREAD

**Issue by thejayps** [Ravenbrook/mps#215]
This issue is described here: https://www.ravenbrook.com/project/mps/custom/cet/main/manual/html/custom/cet/hasharray.html

A solution is also described above and has been implemented for a client's custom MPS.

**Comment by thejayps** [comment]
Further information on requirements from discussion with Configura:
- Hash arrays are used pretty much "everywhere all the time" (quote from @thejayps notes). 
- The solution provided has been an effective functional workaround to the problem except for pathological situations (creating a hash table of every object in memory for a debugging tool)
- Configura don't report any performance issues with the solution provided so far.

**Comment by rptb1** [comment]
The interface and implementation might be improved by providing a way to "reallocate" an object, in the sense that the client can inform the MPS that a new object has the same mortality properties as an existing object.  In this case, the mutator would allocate the new hash array with the same props as the old one, and the MPS could place it in e.g. the same generation.  This would be a general interface not restricted to the rehashing problem.
