### ISSUE TITLE
The MPS does not provide a method for finding the address of an object from an interior pointer

### ISSUE THREAD

**Issue by thejayps** [Ravenbrook/mps#216]
This capability is useful for debugging and stack tracing for clients who allocate objects on the heap containing code.

We have implemented "mps_addr_object" for Configura to provide this capability for them.

**Comment by rptb1** [comment]
See also [job003589](https://info.ravenbrook.com/project/cet/issue/job003589/) for the original requirements, and [branch/2013-10-21/cet-addr-to-obj](https://info.ravenbrook.com/project/mps/branch/2013-10-21/cet-addr-to-obj/) for the original implementation.
