### ISSUE TITLE
Arena extension and contraction callbacks are called inconsistently

### ISSUE THREAD

**Issue by thejayps** [Ravenbrook/mps#227]
Arena extenstion callback is called after an arena is created, i.e. the creation is treated as an extension.

Arena contraction callback is not called when the arena is destroyed (we also might violate the 1-1 nature of extensions/contractions if we destroy an arena that has been created then extended beyond its original size).

We should decide on something that's consistent and works with the underlying requirement: https://github.com/Ravenbrook/mps/issues/212

**Comment by rptb1** [comment]
We should check with our main client whether adding a callback on destroy would affect them (I believe not) and fix this in #213 if not.

**Comment by rptb1** [comment]
Fixed by https://github.com/Ravenbrook/mps/pull/213/commits/fb93d8616d8b5db175037d201230c6bbc28ec067
