### ISSUE TITLE
cleaner api

### ISSUE THREAD

**Issue by mgood7123** [Ravenbrook/mps#262]
how might we implement a cleaner api similar to Java while also considering MPS's current limitations and intended usage ?

[Finalization and Weak, Soft, and Phantom References (docs.oracle.com/en/java/javase/20) ](https://docs.oracle.com/en/java/javase/20/gctuning/other-considerations.html#GUID-A7B0991C-661F-47BE-AEDB-74C6BDBDE181)

[JEP 421: Deprecate Finalization for Removal (openjdk.org/jeps) ](https://openjdk.org/jeps/421)

[JAVA 20 - java.lang.Cleaner (docs.oracle.com/en/java/javase/20)](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/ref/Cleaner.html)

[Java Cleaners (java/basics/java-cleaners - how to use)](https://howtodoinjava.com/java/basics/java-cleaners/)

(tho such api would be more time consuming to specify with an object class compared to simply `registering for finalization and then handling the finalization`)

also while not everything in jvm's gc applies to MPS, some concepts should be noted

(such as weak references needed by dylan, possibly originally inspired by java or some other language that provides them, and then ported over to and implemented in dylan, and then made public via MPS)

**Comment by rptb1** [comment]
One significant think about JVM finalzation that you will have read is that they're removing it.  And for good reason.  The same reasons, in fact, that I described in https://github.com/Ravenbrook/mps/issues/259#issuecomment-1731592474 .  All GCs have the same issue: when you provide finalization (which is based on *memory*) people start to press it in to use to reliably manage external resource.  It is not a suitable tool for that.  I'm sure the Java people have realized this and decided to remove it.

You'll note that registering objects for "cleaning" is basically like [mps_finalize()](https://memory-pool-system.readthedocs.io/en/latest/topic/finalization.html#c.mps_finalize) and cleaning actions are basically run when the equivalent of [mps_message_type_finalization()](https://memory-pool-system.readthedocs.io/en/latest/topic/finalization.html#c.mps_message_type_finalization) is received.

On a historical note, Dylan was a direct competitor to Java, and was originally supported by Apple.  But Java won the game.  The MPS pre-dates Java and its design owes more to the [Lisp Machine](https://en.wikipedia.org/wiki/Lisp_machine) than Java.  Nothing in Dylan was "ported over" from Java.  Most of it was inherited from Lisp and Scheme.  Harlequin, the company that developed Dylan (and originally the MPS) was a major Lisp vendor.

**Comment by mgood7123** [comment]
> On a historical note, Dylan was a direct competitor to Java, and was originally supported by Apple.  But Java won the game.  The MPS pre-dates Java and its design owes more to the [Lisp Machine](https://en.wikipedia.org/wiki/Lisp_machine) than Java.  Nothing in Dylan was "ported over" from Java.  Most of it was inherited from Lisp and Scheme.  Harlequin, the company that developed Dylan (and originally the MPS) was a major Lisp vendor.

Wow

**Comment by mgood7123** [comment]
> You'll note that registering objects for "cleaning" is basically like [mps_finalize()](https://memory-pool-system.readthedocs.io/en/latest/topic/finalization.html#c.mps_finalize) and cleaning actions are basically run when the equivalent of [mps_message_type_finalization()](https://memory-pool-system.readthedocs.io/en/latest/topic/finalization.html#c.mps_message_type_finalization) is received.

Doesn't this contradict itself?

**Comment by mgood7123** [comment]
Welp, even though resurrection is very undesirable

it CANNOT be obliterated since there are valid use cases for it

such as COM/STA interop and apple api interop (very strong calling-thread requirements)

**Comment by rptb1** [comment]
Added pending label so we can consider improvements to documentation.
