### ISSUE TITLE
object format scanner with closure

### ISSUE THREAD

**Issue by mgood7123** [Ravenbrook/mps#264]
how would i arrange for a closure to be passed with object format scanner in order to access non-global state ?

**Comment by mgood7123** [comment]
for now imma just make use of `LockClaimGlobalRecursive` and `LockReleaseGlobalRecursive` to initialize globals

**Comment by rptb1** [comment]
Please note well the [restrictions on format methods](https://memory-pool-system.readthedocs.io/en/latest/topic/format.html#cautions) including scanners.  You can't look at arbitrary memory during a scan.

**Comment by mgood7123** [comment]
> Please note well the [restrictions on format methods](https://memory-pool-system.readthedocs.io/en/latest/topic/format.html#cautions) including scanners.  You can't look at arbitrary memory during a scan.

True

**Comment by mgood7123** [comment]
> Please note well the [restrictions on format methods](https://memory-pool-system.readthedocs.io/en/latest/topic/format.html#cautions) including scanners.  You can't look at arbitrary memory during a scan.

Tho the scheme example uses the static variable `obj_deleted` during scanning of the hash table, right?
