### ISSUE TITLE
Warnings when compiling in Visual Studio 2008 (and probably other versions)

### ISSUE THREAD

**Issue by fstromback** [Ravenbrook/mps#30]
After the commit 83fc9a51e72976f7b96f8c20ff1465aace709d17 changed the macro GenDescOfTraceRing, the macro generates the following warning in Visual Studio 2008 when compiled with /W2 or higher:

```
  mps\code\trace.c(432) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
  mps\code\trace.c(785) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
  mps\code\trace.c(872) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
  mps\code\trace.c(1844) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
```

This can be fixed by, for example, adding a typecast to the definition in `locus.h` as follows:
`#define GenDescOfTraceRing(node, tr) PARENT(GenDescStruct, trace, &RING_ELT(GenTrace, traceRing, node)[-(int)tr->ti])`
There may be better solutions though.

**Comment by gareth-rees** [comment]
Thanks for reporting this. I don't have Visual C/C++, so could you try out this alternative fix?
```
#define GenDescOfTraceRing(node, tr) PARENT(GenDescStruct, trace, RING_ELT(GenTrace, traceRing, node) - tr->ti)
```

**Comment by fstromback** [comment]
Perfect, that does not generate the warning either, and looks much nicer. Thank you!
