### ISSUE TITLE
Explanation needed for why we turn on so many warnings

### ISSUE THREAD

**Issue by gareth-rees** [Ravenbrook/mps#53]
The compiler makefile fragments (gc.gmk, ll.gmk, mv.nmk) turn on many warnings along with turning warnings into errors (`-Werror` for GCC and Clang; `/WX` for Microsoft Visual C). There is an important reason why we do this, namely that we recommend [Optimizing for your object format](https://www.ravenbrook.com/project/mps/master/manual/html/guide/build.html#optimizing-for-your-object-format):

> If you are using your own object format, you will also get improved performance by allowing the compiler to do global optimizations between it and the MPS. So if your format implementation is in, say, myformat.c, then you could make a file mymps.c containing:
> ```
> #include "mps.c"
> #include "myformat.c"
> ```
> This will get your format code inlined with the MPS garbage collector.

In order for this to work, the MPS must be able to compile *with whatever compilation and warning options the user has turned on*. This is why we turn on many warning options in our own Makefiles, in order to catch and fix warnings before they are encountered by users.

This is an important requirement and so needs a mention in a design document, and should be cross-referenced from the compiler makefile fragments.

**Comment by rptb1** [comment]
I think it's worth mentioning:
1. The secondary reason we have historically used `-Werror` internally: as an early warning of subtle compiler issues that break memory managers, and to ensure we do not accidentally merge harmful changes.
2. A note about how someone could change this behaviour locally, e.g. by editing https://github.com/Ravenbrook/mps/blob/d13e2855bfeceaa14b942e7b9e90af7a15de04ad/code/ll.gmk#L21 etc.
